import { Poppins } from "next/font/google";
import "./globals.css";
import { connectToDataBase } from "@/dbconnect/connector";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "./contexts";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "khanaKhazana",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectToDataBase();

  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
